- name: Install nginx
  hosts: Web
  become: yes
  tasks:
  - name: Install nginx in web server
    ansible.builtin.package:
      name: nginx
      state: present
  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes


